name: Actualizar Actividad Reciente

on:
  schedule:
    - cron: '0 */6 * * *'  # Se ejecuta cada 6 horas
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README activity
        uses: Readme-Workflows/recent-activity@v2.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 10
          COMMIT_MSG: 'Update recent activity in README'
          COMMIT_USERNAME: 'github-actions[bot]'
          COMMIT_EMAIL: 'github-actions[bot]@users.noreply.github.com'
