name: Actualizar Actividad Reciente

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Se cambió LIMIT_TO por MAX_LINES que es el input válido
          MAX_LINES: 5
          COMMIT_NAME: 'github-actions[bot]'
          COMMIT_EMAIL: 'github-actions[bot]@users.noreply.github.com'
